services:
  # PostgreSQL Servisi
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - '61508:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Zookeeper Servisi (Kafka için gerekli)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Confluent Zookeeper imajı
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - app-network

  # Kafka Servisi
  kafka:
    image: confluentinc/cp-kafka:latest  # Confluent Kafka imajı
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
